### ISSUE TITLE
Create TodoItem service.

### ISSUE THREAD

**Issue by yoanpetrov02** [yoanpetrov02/todo-app#16]
Create interfaces for the services and their respective implementations. For now we will only implement CRUD methods for access to the database.

**Comment by yoanpetrov02** [comment]
Created a branch, `16-create-todoitem-service`, for the changes here.

**Comment by SilvioStoykov** [comment]
You can close this one, as I resolved this in another issue :#

**Comment by SilvioStoykov** [comment]
Closing this issue as it is resolved in #21.
